runtime: custom
env: flex

# ההוראה להריץ את ה-WSGI server
entrypoint: gunicorn -k gthread \
    --workers 1 \
    --threads 4 \
    --bind 0.0.0.0:$PORT \
    --timeout 1200 \
    app:app

# משאבים
resources:
  disk_size_gb: 50

# מתי נחשיב את האפליקציה מוכנה
readiness_check:
  app_start_timeout_sec: 1200
